version: '2.1'
services:
  database:
    image: "mysql:5.7.18"
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --port=$MYSQL_CONTAINER_PORT]
    expose:
      - "${MYSQL_CONTAINER_PORT}"
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  server:
    build:
      context: ./server
    environment:
      - CONNECT_STRING
      - SECRET_KEY
      - APPSERVER_CONTAINER_PORT
    expose:
      - "${APPSERVER_CONTAINER_PORT}"
    volumes:
      - ./server/src:/app
      - ./openapi:/openapi
    depends_on:
      database:
        condition: service_healthy
  web:
    build:
      context: ${WEBSERVER_CONTEXT_DIR}
    ports:
      - "${WEBSERVER_HOST_PORT}:${WEBSERVER_CONTAINER_PORT}"
    volumes:
      - ./web:/app/
    links:
      - server
#  web:
#    image: "rgoyard/apache-proxy:latest"
#    ports:
#      - "${WEBSERVER_HOST_PORT}:${WEBSERVER_CONTAINER_PORT}"
#    volumes:
#      - ${WEBSERVER_CONF}:/conf/
#      - ./web:/app/
#    links:
#      - server
